[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "learn-rust"
path = "./src/ownership.rs"

[[bin]]
name = "learn-rust"
path = "./src/borrowing.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
